# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
import tree_pb2 as tree__pb2


class TreeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBase = channel.unary_unary(
                '/Tree/CreateBase',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=tree__pb2.SuccessResponse.FromString,
                )
        self.CreateTable = channel.unary_unary(
                '/Tree/CreateTable',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=tree__pb2.SuccessResponse.FromString,
                )
        self.CreateRows = channel.unary_unary(
                '/Tree/CreateRows',
                request_serializer=tree__pb2.CreateRowsRequest.SerializeToString,
                response_deserializer=tree__pb2.SuccessResponse.FromString,
                )
        self.CreateColumns = channel.unary_unary(
                '/Tree/CreateColumns',
                request_serializer=tree__pb2.CreateColumnsRequest.SerializeToString,
                response_deserializer=tree__pb2.SuccessResponse.FromString,
                )
        self.ReadTree = channel.unary_unary(
                '/Tree/ReadTree',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                )
        self.ReadBase = channel.unary_unary(
                '/Tree/ReadBase',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                )
        self.ReadTable = channel.unary_unary(
                '/Tree/ReadTable',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                )
        self.ReadRows = channel.unary_unary(
                '/Tree/ReadRows',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                )
        self.ReadColumns = channel.unary_unary(
                '/Tree/ReadColumns',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                )
        self.ReadRow = channel.unary_unary(
                '/Tree/ReadRow',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.ListValue.FromString,
                )
        self.ReadColumn = channel.unary_unary(
                '/Tree/ReadColumn',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.ListValue.FromString,
                )
        self.ReadValue = channel.unary_unary(
                '/Tree/ReadValue',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.ListValue.FromString,
                )
        self.ReadSchema = channel.unary_unary(
                '/Tree/ReadSchema',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                )
        self.UpdateRow = channel.unary_unary(
                '/Tree/UpdateRow',
                request_serializer=tree__pb2.UpdateRowRequest.SerializeToString,
                response_deserializer=tree__pb2.SuccessResponse.FromString,
                )
        self.UpdateColumn = channel.unary_unary(
                '/Tree/UpdateColumn',
                request_serializer=tree__pb2.UpdateColumnRequest.SerializeToString,
                response_deserializer=tree__pb2.SuccessResponse.FromString,
                )
        self.DeleteBase = channel.unary_unary(
                '/Tree/DeleteBase',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=tree__pb2.SuccessResponse.FromString,
                )
        self.DeleteTable = channel.unary_unary(
                '/Tree/DeleteTable',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=tree__pb2.SuccessResponse.FromString,
                )
        self.DeleteRow = channel.unary_unary(
                '/Tree/DeleteRow',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=tree__pb2.SuccessResponse.FromString,
                )
        self.DeleteColumn = channel.unary_unary(
                '/Tree/DeleteColumn',
                request_serializer=tree__pb2.PathRequest.SerializeToString,
                response_deserializer=tree__pb2.SuccessResponse.FromString,
                )
        self.IntersectTables = channel.unary_unary(
                '/Tree/IntersectTables',
                request_serializer=tree__pb2.IntersectTablesRequest.SerializeToString,
                response_deserializer=tree__pb2.SuccessResponse.FromString,
                )


class TreeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBase(self, request, context):
        """Create
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateColumns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadTree(self, request, context):
        """Read
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadColumns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadColumn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRow(self, request, context):
        """Update
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateColumn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBase(self, request, context):
        """Delete
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteColumn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IntersectTables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TreeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBase,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=tree__pb2.SuccessResponse.SerializeToString,
            ),
            'CreateTable': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTable,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=tree__pb2.SuccessResponse.SerializeToString,
            ),
            'CreateRows': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRows,
                    request_deserializer=tree__pb2.CreateRowsRequest.FromString,
                    response_serializer=tree__pb2.SuccessResponse.SerializeToString,
            ),
            'CreateColumns': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateColumns,
                    request_deserializer=tree__pb2.CreateColumnsRequest.FromString,
                    response_serializer=tree__pb2.SuccessResponse.SerializeToString,
            ),
            'ReadTree': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadTree,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'ReadBase': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBase,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'ReadTable': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadTable,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'ReadRows': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRows,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'ReadColumns': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadColumns,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'ReadRow': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRow,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.ListValue.SerializeToString,
            ),
            'ReadColumn': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadColumn,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.ListValue.SerializeToString,
            ),
            'ReadValue': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadValue,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.ListValue.SerializeToString,
            ),
            'ReadSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSchema,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'UpdateRow': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRow,
                    request_deserializer=tree__pb2.UpdateRowRequest.FromString,
                    response_serializer=tree__pb2.SuccessResponse.SerializeToString,
            ),
            'UpdateColumn': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateColumn,
                    request_deserializer=tree__pb2.UpdateColumnRequest.FromString,
                    response_serializer=tree__pb2.SuccessResponse.SerializeToString,
            ),
            'DeleteBase': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBase,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=tree__pb2.SuccessResponse.SerializeToString,
            ),
            'DeleteTable': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTable,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=tree__pb2.SuccessResponse.SerializeToString,
            ),
            'DeleteRow': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRow,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=tree__pb2.SuccessResponse.SerializeToString,
            ),
            'DeleteColumn': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteColumn,
                    request_deserializer=tree__pb2.PathRequest.FromString,
                    response_serializer=tree__pb2.SuccessResponse.SerializeToString,
            ),
            'IntersectTables': grpc.unary_unary_rpc_method_handler(
                    servicer.IntersectTables,
                    request_deserializer=tree__pb2.IntersectTablesRequest.FromString,
                    response_serializer=tree__pb2.SuccessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Tree', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tree(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/CreateBase',
            tree__pb2.PathRequest.SerializeToString,
            tree__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/CreateTable',
            tree__pb2.PathRequest.SerializeToString,
            tree__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/CreateRows',
            tree__pb2.CreateRowsRequest.SerializeToString,
            tree__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateColumns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/CreateColumns',
            tree__pb2.CreateColumnsRequest.SerializeToString,
            tree__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/ReadTree',
            tree__pb2.PathRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadBase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/ReadBase',
            tree__pb2.PathRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/ReadTable',
            tree__pb2.PathRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/ReadRows',
            tree__pb2.PathRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadColumns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/ReadColumns',
            tree__pb2.PathRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/ReadRow',
            tree__pb2.PathRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.ListValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadColumn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/ReadColumn',
            tree__pb2.PathRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.ListValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/ReadValue',
            tree__pb2.PathRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.ListValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/ReadSchema',
            tree__pb2.PathRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/UpdateRow',
            tree__pb2.UpdateRowRequest.SerializeToString,
            tree__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateColumn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/UpdateColumn',
            tree__pb2.UpdateColumnRequest.SerializeToString,
            tree__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/DeleteBase',
            tree__pb2.PathRequest.SerializeToString,
            tree__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/DeleteTable',
            tree__pb2.PathRequest.SerializeToString,
            tree__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/DeleteRow',
            tree__pb2.PathRequest.SerializeToString,
            tree__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteColumn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/DeleteColumn',
            tree__pb2.PathRequest.SerializeToString,
            tree__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IntersectTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tree/IntersectTables',
            tree__pb2.IntersectTablesRequest.SerializeToString,
            tree__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
